import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ThemeProvider.tsx";
import WebCamProvider from "@/app/_components/WebCamProvider"; // ✅ IMPORTANT

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          
          {/* ✅ Wrap EVERYTHING inside provider */}
          <WebCamProvider>

            <Toaster />

            <ThemeProvider
              attribute="class"
              defaultTheme="white"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>

          </WebCamProvider>

        </body>
      </html>
    </ClerkProvider>
  );
}